language: java

addons:
  sonarcloud:
    organization: "lost1227"
    token:
      secure: "AAgRbK/TnGaz+ubHPOSjjj3b1TF6R94aOSVUz37d2ZccyoGX091kggg8slCcY1x3rJDD64gsisKFqSR2iq81wiINexQlSO4gMxncJN9Izqd1MFhqvwy3GgjcuupXax16fTYHF/rh1X9I3vcZLIAAhPOgv/vr0nTvA0rViHEeTd/0lOBciSbfCEzYKVmsjCTv7nChMIT3hXRgfSHox7KI6RDQl8+Qd5FJ+qWyJYuTO0V7caCOnFPcjJ638SUNgbI+q+EtowL/GTJSPpTNRz8grZxNp8MtqrIsB8fCl96yuP5dSvqj2xmndqPsuf0JRCKjWc8f8haVv+Lb5ir883hnuBRqCnw1vmB/p6JeNZBa83DUuFJ6cZbuW/onWJvdcdoOehRsW2zhhd2jBkmjUAjjbxfIB/Zwu6yTOsTLdcZbs/ERL2HEHQa/kFrALEJsVzYtuWKPK00QzzbcFJ9QVA/wGlZ7WBgSZes/JhaWUXWWihzxBUqJk9zuYLkzt60ytsBx5AydZqazTn0N0jQBejQpvKzyXoJSp+W6YM6a62nRlS07Al+b6U1mNknHvcYOPBY3ziMs/WqkNy4GxB5jk8G/JVTtUU/CLFxE8XAH5R74MlFlNqG55BfJzTiFT8Yewg766qJqyStwvE0I7qUvzYJ+td9ry0h/oBIBd7O0a4xJfOU="
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      
jdk:
  - openjdk8

script:
  - ./gradlew sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
    - 'ui/.gradle'
    - 'ui/node_modules'