language: java
jdk:
- openjdk8

addons:
  sonarcloud:
    organization: "lost1227"
    token:
      secure: "tZbz9TvFfbqwdCZMynx5AtljX89hTXFiFWRUXg3mnaUJX/LGMHupHZm9kOR8I9w9ZXoNmLNZQBkr6m3U3pBN+QIiB0nyEzrKm/3zrDg9jH9OqADdHzkE1qGReKw6SDFQO7E37IUyHEoCZ+4NcRYoLVvxnJGpiQbEb2Kg1vz3rraN9A8UqXsbs75mxrEKdk1LNzb1VUy4WzTMJ2Mg+TnalVK+a4QyeCn9iLKgkPZjqEdvCvxJlCBeRx7vo9yT3LXhJ0ZDPfzNWwbs+Nxw9uzSnwk/s8yscrvTA6T0t7T9XqZxvCQl+saGjeAHLy1ro4X7iZdR+7XwKK7GdFbbXRf6QcIdNk+y+6DaiW26x0FgQ0h+e9VJTjdKVvLGcD++3QLiqudl/jkjYHRN0MRID5lY/Pcdjellh3mYddx/sbpP8lstoCRL8bSghEKI8Ph9jxyjVT06mp/yGiP1+PohGeLE4lmgpKHSYbPJsdZ5i791vEBAYZWU4n6jRxc8uoIMn6/1BCifTcvg6Jj7APF3oWieF7WyQPAq4Skj6/oxhyRH5C9LHMpTsuskic5zKx0tZWJYC5BFjd8/F0BGa9heaVkzHJduviMSM+sThG07qttOD32WZOUOGhnqad0XAmtvyPWbpEiRecdhdX0E71y15ut5bEDCBFkVz++RXnj3Ea9LrCA="


script:
- ./gradlew sonarqube